[versions]
androidx-hilt = "1.3.0"
androidx-work = "2.11.0"
hilt = "2.57.2"
kotlin = "2.2.21"
kotlin-ksp = "2.3.0"
screenshot = "0.0.1-alpha11"

[libraries]
androidx-compose = { module = "androidx.compose:compose-bom", version = "2025.10.01" }
androidx-compose-activity = { module = "androidx.activity:activity-compose", version = "1.11.0" }
androidx-compose-constraintLayout = { module = "androidx.constraintlayout:constraintlayout-compose", version = "1.1.1" }
androidx-compose-material = { module = "androidx.compose.material3:material3" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-extended", version = "1.7.8" }
androidx-compose-uiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-uiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version = "1.1.7" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidx-hilt" }
androidx-hilt-workManager = { module = "androidx.hilt:hilt-work", version.ref = "androidx-hilt" }
androidx-startUp = { module = "androidx.startup:startup-runtime", version = "1.2.0" }
androidx-test-core = { module = "androidx.test:core-ktx", version = "1.7.0" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.7.0" }
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version = "1.3.0" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.7.0" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.7.0" }
androidx-tracing = { module = "androidx.tracing:tracing", version = "1.3.0" }
androidx-work = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
androidx-work-test = { module = "androidx.work:work-testing", version.ref = "androidx-work" }
composable-icons = { module = "com.composables:icons-lucide", version = "1.1.0" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
junit = { module = "junit:junit", version = "4.13.2" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version = "1.10.2" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.9.0" }
okhttp = { module = "com.squareup.okhttp3:logging-interceptor", version = "5.3.0" }
retrofit = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version = "3.0.0" }
solarevents = { module = "org.shredzone.commons:commons-suncalc", version = "3.11" }
screenshot-validation-api = { module = "com.android.tools.screenshot:screenshot-validation-api", version.ref = "screenshot" }
screenshot-validation-engine = { module = "com.android.tools.screenshot:screenshot-validation-junit-engine", version.ref = "screenshot" }

[bundles]
screenshot-validation = ["screenshot-validation-api", "screenshot-validation-engine"]

[plugins]
android = { id = "com.android.application", version = "8.11.1" }
embeddedDependencies = { id = "io.github.gmazzo.dependencies.embedded", version = "1.1.0" }
firebase-testlab = { id = "com.google.firebase.testlab", version = "0.0.1-alpha12" }
gitVersion = { id = "io.github.gmazzo.gitversion", version = "1.5.1" }
googlePlayPublish = { id = "com.github.triplet.play", version = "3.12.1" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
keeper = { id = "com.slack.keeper", version = "0.16.1" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "kotlin-ksp" }
kotlin-seriazliation = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
screenshot = { id = "com.android.compose.screenshot", version.ref = "screenshot" }
test-aggregation-coverage = { id = "io.github.gmazzo.test.aggregation.coverage", version = "2.4.6" }
